<?php
$config = require './Runtime/Conf/config.php';
$array = array(
	'USER_AUTH_KEY'=>'ffvod',// 用户认证SESSION标记
	'NOT_AUTH_ACTION'=>'index,show,add,top,left,main',// 默认无需认证操作
	'REQUIRE_AUTH_MODULE'=>'Admin,List,Vod,News,User,Collect,Data,Upload,Link,Ads,Cache,Create,Tpl,Cm,Gb,Tag,Special,Nav,Side,Pic',// 默认需要认证模型
    'URL_PATHINFO_DEPR'=>'-',
	'DEFAULT_C_LAYER'=>  'Action', // 默认的控制器层名称
	'MODULE_ALLOW_LIST'=>array('Admin','Home','Plus','User'),//项目分组
	'DEFAULT_M_LAYER'=>  'Model', // 默认的模型层名称
	'VIEW_PATH'=>'./Tpl/',
	'TMPL_FILE_DEPR'=>'_',//模板文件MODULE_NAME与ACTION_NAME之间的分割符，只对项目分组部署有效
	'TMPL_STRIP_SPACE'=> true,// 是否去除模板文件里面的html空格与换行
	'LANG_SWITCH_ON'=>true,// 多语言包功能
	'LANG_AUTO_DETECT'=>false,//是否自动侦测浏览器语言
	'URL_CASE_INSENSITIVE'=>true,//URL是否不区分大小写 默认区分大小写
    'DB_FIELDTYPE_CHECK'=>true, //是否进行字段类型检查
	'DATA_CACHE_SUBDIR'=>true,//哈希子目录动态缓存的方式
	'SHOW_ERROR_MSG'=>true, //关闭错误输出
    'TMPL_ACTION_ERROR'     => './Public/jump/jumpurl.html', // 默认错误跳转对应的模板文件
    'TMPL_ACTION_SUCCESS'   => './Public/jump/jumpurl.html', // 默认成功跳转对应的模板文件		
	'DATA_PATH_LEVEL'=>2,
  	'url_model' => '3',
	'play_player' =>array (
		'ffhd'=>    array('00','非凡影音'),
		'xigua'=>   array('02','西瓜影音'),
		'xfplay'=>  array('03','影音先锋'),
		'jjvod'=>   array('04','吉吉影音'),
		'yuku'=>    array('05','优酷视频'),
		'tudou'=>   array('06','土豆视频'),
		'qiyi'=>    array('01','奇艺视频'),
		'letv'=>    array('08','乐视视频'),
		'sohu'=>    array('09','搜狐视频'),
		'qq'=>      array('10','腾讯视频'),
		'xunlei'=>   array('11','迅雷高清'),
		'm1905'=>   array('99','M1905'),
		'sinahd'=>  array('12','新浪视频'),
		'cntv'=>    array('13','cntv高清'),
		'pps'=>     array('14','PPS视频'),
		'wole'=>    array('15','56视频'),
		'joy'=>     array('16','激动视频'),
		'room'=>    array('17','六间房'),
		'pptv'=>    array('18','PPTV视频'),
		'ku6'=>     array('19','酷六视频'),
		'down'=>    array('20','影片下载'),
		'swf'=>     array('21','Swf动画'),
		'flv'=>     array('22','Flv视频'),
		'web9'=>    array('23','久久影音'),
		'pvod'=>    array('24','皮皮高清'),
		'cool'=>    array('25','酷播高清'),
		'gvod'=>    array('26','迅播高清'),
		'funshion'=>array('27','风行影音'),
		'baofeng'=> array('28','暴风影音'),
		'pplive'=>  array('29','PPTV直播'),
		'media'=>   array('30','Media Player'),
		'real'=>    array('31','Real Player'),
		'qvod'=>    array('32','快播高清'),
        'kankan'=>  array('33','迅雷看看'),
		'mgtv'=>    array('34','芒果TV'),
		'bdhd'=>    array('35','百度影音'),
	),
	//'APP_DEBUG'           =>true,    // 是否开启调试模式
   // 'SHOW_RUN_TIME'		=> true,   // 运行时间显示
    //'SHOW_ADV_TIME'		=> true,   // 显示详细的运行时间
   // 'SHOW_DB_TIMES'		=> true,   // 显示数据库查询和写入次数	
);
return array_merge($config,$array);
?>